# Generated by Django 2.2.7 on 2020-04-21 03:02

from django.db import migrations, models
import django.db.models.deletion
import libreria.models.libros


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VLibroautores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('titulo', models.CharField(blank=True, max_length=70, null=True)),
                ('autores', models.TextField(blank=True, db_column='Autores', null=True)),
            ],
            options={
                'db_table': 'v_libroautores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'libreria_editorial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=70, validators=[libreria.models.libros.validar_titulo])),
                ('paginas', models.PositiveIntegerField(db_index=True)),
                ('fecha_publicacion', models.DateField(null=True)),
                ('imagen', models.URLField(max_length=85, null=True)),
                ('desc_corta', models.CharField(default='Sin reseña', max_length=2000)),
                ('estatus', models.CharField(choices=[('P', 'Publish'), ('M', 'MEAP')], max_length=1)),
                ('categoria', models.CharField(max_length=50)),
                ('edicion_anterior', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreria.Libro')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.Editorial')),
            ],
        ),
        migrations.CreateModel(
            name='LibroCronica',
            fields=[
                ('descripcion_larga', models.TextField(null=True)),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='libreria.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='AutorCapitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_capitulos', models.IntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.Autor')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.Libro')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='libro',
            field=models.ManyToManyField(related_name='libros_autores', through='libreria.AutorCapitulo', to='libreria.Libro'),
        ),
        migrations.AddConstraint(
            model_name='libro',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, titulo='cobol'), name='titulo_no_permitido_chk'),
        ),
    ]
