# Generated by Django 2.2.7 on 2019-11-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('titulo', models.CharField(max_length=70)),
                ('paginas', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.URLField(max_length=85)),
                ('desc_corta', models.CharField(max_length=2000)),
                ('estatus', models.CharField(choices=[('P', 'Publish'), ('M', 'MEAP')], max_length=1)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
