# Generated by Django 2.2.7 on 2019-11-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='desc_corta',
            field=models.CharField(default='Sin reseña', max_length=2000),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.URLField(max_length=85, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
