# Generated by Django 2.2.7 on 2019-11-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20191125_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='id',
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
