# Generated by Django 2.2.7 on 2020-09-10 06:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20191228_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='detalles',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
