# Generated by Django 2.2.7 on 2021-02-23 03:47

from django.db import migrations


def cargar_script_procedimiento():
    from orm_sqlfan.settings import BASE_DIR
    import os
    sql_scripts = open(os.path.join(BASE_DIR,'libreria/sql/mi_funcion.sql'), 'r').read()
    return sql_scripts



class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_auto_20191228_0625'),
    ]

    operations = [
         migrations.RunSQL(cargar_script_procedimiento(),)
    ]
