# Generated by Django 2.2.7 on 2020-11-23 02:06

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_libro_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='dsc_corta_token',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
