# Generated by Django 2.2.7 on 2019-11-25 05:41

from django.db import migrations, models
import libreria.models.libros


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_auto_20191125_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, max_length=70, validators=[libreria.models.libros.validar_titulo]),
        ),
    ]
