# Generated by Django 2.2.7 on 2020-11-25 21:14

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_libro_dsc_corta_token'),
    ]

    operations = [
        TrigramExtension(),
    ]
