# Generated by Django 2.2.7 on 2019-11-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_auto_20191125_0541'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='libro',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, titulo='cobol'), name='titulo_no_permitido_chk'),
        ),
    ]
