# Generated by Django 2.2.7 on 2020-12-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0006_auto_20201125_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='dsc_corta_token',
        ),
    ]
