# Generated by Django 2.2.7 on 2020-12-07 23:19

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_remove_libro_dsc_corta_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='dsc_corta_token',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
