# Generated by Django 2.2.7 on 2019-11-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_editorial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='editorial',
            table='libreria_editorial',
        ),
    ]
