# Generated by Django 2.2.7 on 2020-12-07 23:30

from django.db import migrations

def cargar_script_columna_Searchvector():
    from orm_sqlfan.settings import BASE_DIR
    import os
    sql_scripts = open(os.path.join(BASE_DIR,'libreria/sql/columna_SearchVectorField.sql'), 'r').read()
    return sql_scripts


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_libro_dsc_corta_token'),
    ]

    operations = [
         migrations.RunSQL(cargar_script_columna_Searchvector(),)
    ]

