# Generated by Django 2.2.7 on 2019-12-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_auto_20191129_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='edicion_anterior',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='libreria.Libro'),
        ),
    ]
