# Generated by Django 2.2.7 on 2019-12-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0009_libro_edicion_anterior'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCronica',
            fields=[
                ('descripcion_larga', models.TextField(null=True)),
                ('libro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='libreria.Libro')),
            ],
        ),
    ]
