# Generated by Django 2.2.7 on 2019-12-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_librocronica'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='libreria.Editorial'),
            preserve_default=False,
        ),
    ]
