# Generated by Django 2.2.7 on 2019-12-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_autor_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='libro',
            field=models.ManyToManyField(related_name='autores', to='libreria.Libro'),
        ),
    ]
