# Generated by Django 2.2.7 on 2019-12-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_auto_20191208_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='libro',
        ),
    ]
