# Generated by Django 2.2.7 on 2019-12-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_remove_autor_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorCapitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_capitulos', models.IntegerField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.Autor')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.Libro')),
            ],
        ),
    ]
