# Generated by Django 2.2.7 on 2019-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_autorcapitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='libro',
            field=models.ManyToManyField(related_name='libros_autores', through='libreria.AutorCapitulo', to='libreria.Libro'),
        ),
    ]
