# Generated by Django 2.2.7 on 2019-12-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_autor_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorcapitulo',
            name='numero_capitulos',
            field=models.IntegerField(default=0),
        ),
    ]
