# Generated by Django 3.1.7 on 2021-06-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0016_autor_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='editorial',
            name='pais',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autorcapitulo',
            name='numero_capitulos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libro_editorial', to='libreria.editorial'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
