# Generated by Django 3.1.7 on 2021-06-16 17:18


from django.db import migrations

def cargar_datos_desde_sql():
    from orm_sqlfan.settings import BASE_DIR
    import os
    sql_script = open(os.path.join(BASE_DIR,'libreria/sql/migracion.sql'),'r').read()
    return sql_script


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_auto_20210616_1214'),
    ]

    operations = [
        migrations.RunSQL(cargar_datos_desde_sql(),)
    ]
