# Generated by Django 2.2.7 on 2019-12-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_auto_20191210_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorcapitulo',
            name='numero_capitulos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='paginas',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
