# Generated by Django 2.2.24 on 2022-06-26 23:47

from django.db import migrations, models
import django.db.models.deletion
import libreria.models.editoriales


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_auto_20191220_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLibroautores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('titulo', models.CharField(blank=True, max_length=70, null=True)),
                ('autores', models.TextField(blank=True, db_column='Autores', null=True)),
            ],
            options={
                'db_table': 'v_libroautores',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='editorial',
            name='nombre_corto',
            field=models.CharField(default='', max_length=40, validators=[libreria.models.editoriales.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libro_editorial', to='libreria.Editorial'),
        ),
    ]
