# Generated by Django 2.2.7 on 2019-12-28 06:25

from django.db import migrations


def cargar_script_vista():
    from orm_sqlfan.settings import BASE_DIR
    import os
    sql_scripts = open(os.path.join(BASE_DIR,'libreria/sql/vista_libros_autor.sql'), 'r').read()
    return sql_scripts



class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_auto_20191220_2054'),
    ]

    operations = [
        migrations.RunSQL(cargar_script_vista(),)
    ]
