# Generated by Django 3.1.7 on 2021-06-16 17:21

from django.db import migrations

def cargar_script_vista():
    from orm_sqlfan.settings import BASE_DIR
    import os
    sql_scripts = open(os.path.join(BASE_DIR,'libreria/sql/vista_libros_autor.sql'), 'r').read()
    return sql_scripts



class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_auto_20210616_1218'),
    ]

    operations = [
        migrations.RunSQL(cargar_script_vista(),)
    ]

