# Generated by Django 3.1.7 on 2021-06-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_auto_20210616_1221'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='VLibroautores',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('isbn', models.CharField(blank=True, max_length=13, null=True)),
        #         ('titulo', models.CharField(blank=True, max_length=70, null=True)),
        #         ('autores', models.TextField(blank=True, db_column='Autores', null=True)),
        #     ],
        #     options={
        #         'db_table': 'v_libroautores',
        #         'managed': False,
        #     },
        # ),
    ]
