# Generated by Django 2.2.24 on 2022-06-26 23:56

from django.db import migrations
import libreria.models.editoriales


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0019_auto_20220626_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='nombre_corto',
            field=libreria.models.editoriales.NombreCortoField(),
        ),
    ]
