# Generated by Django 2.2.7 on 2021-12-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_vlibroautores'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.BinaryField(default=None, null=True),
        ),
    ]
