# Generated by Django 2.2.24 on 2022-06-26 23:59

from django.db import migrations
import libreria.models.editoriales


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_auto_20220626_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='nombre_corto2',
            field=libreria.models.editoriales.NombreCortoField(),
        ),
    ]
