# Generated by Django 2.2.7 on 2021-11-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0020_vlibroautores'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroPrecio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.DateField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libreria.Libro')),
            ],
        ),
    ]
