# Generated by Django 2.2.7 on 2022-01-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0021_autor_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLibroautores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('titulo', models.CharField(blank=True, max_length=70, null=True)),
                ('autores', models.TextField(blank=True, db_column='Autores', null=True)),
            ],
            options={
                'db_table': 'v_libroautores',
                'managed': False,
            },
        ),
    ]
