# Generated by Django 2.2.7 on 2021-11-23 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0021_libroprecio'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroPrecioCustomManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('libreria.libroprecio',),
        ),
    ]
