# Generated by Django 2.2.24 on 2022-06-27 00:00

from django.db import migrations
import libreria.models.editoriales


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0021_editorial_nombre_corto2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='nombre_corto2',
            field=libreria.models.editoriales.NombreCortoField(default=''),
        ),
    ]
