# Generated by Django 2.2.7 on 2021-11-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_libropreciocustommanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroprecio',
            name='fecha_final',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='libroprecio',
            name='fecha_inicial',
            field=models.DateField(),
        ),
    ]
