# Generated by Django 2.2.7 on 2022-01-09 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_vlibroautores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.CharField(default='Sin comentarios', max_length=2000)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autor_calificacion', to='libreria.Autor')),
            ],
        ),
    ]
