# Generated by Django 2.2.7 on 2021-11-24 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0023_auto_20211122_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroprecio',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='libro_y_precios', to='libreria.Libro'),
        ),
    ]
